[profile.default]
src = "src"
out = "scripts/out/foundry"
cache_path = "scripts/out/cache"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200000
evm_version = "cancun"
bytecode_hash = "ipfs"
gas_reports = ["VolumeDynamicFeeHook"]

[fuzz]
runs = 5000

[fmt]
line_length = 110

# Needed for scripts that read environment variables
fs_permissions = [{ access = "read", path = "./" }]
